# Site settings
title: Motion Lab - Universidad Católica del Uruguay
email: 
description: >-
  Laboratorio de Movimiento Humano de la Universidad Católica del Uruguay.
  El laboratorio cuenta con dos investigadores principales (Dr. Ing. Enrique Ferreira 
  y Dr. Ing. Pablo Iturralde), y colaboradores en otros grupos de investigación.
# Note: baseurl is empty here for local development.
# GitHub Actions workflow overrides this with --baseurl flag during deployment.
baseurl: "/ucumovenglab"
url: "https://UCUmovenglab.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
