# Site settings
title: Motion Lab - Universidad Católica del Uruguay
email: 
description: >-
  Laboratorio de Movimiento Humano de la Universidad Católica del Uruguay.
  El laboratorio cuenta con dos investigadores principales (Dr. Ing. Enrique Ferreira 
  y Dr. Ing. Pablo Iturralde), y colaboradores en otros grupos de investigación.
baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
